spring:
  application:
    name: licensing-server
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://configserver:8071"
  cloud:
    config:
      name: licensing-service
      active: dev
  main:
    allow-bean-definition-overriding: true