spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://configserver:8071"
  cloud:
    config:
      # config server 에서 활성화 시킬 환경 변수 파일
      name: licensing-service #, licensing-service-dev
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG

management.endpoints.enabled-by-default: false
management.endpoint.health:
  enabled: true
  show-details: always


resilience4j.circuitbreaker:
  instances:
    licenseService:
      registerHealthIndicator: true
      # ringBufferSizeInClosedState: 5 => Deprecated
      sliding-window-size: 5 # 닫힌 상태에서의 호출 수로, 서킷을 열어 할지 결정할 때 사용한다.
      # ringBufferSizeInHalfOpenState: 3 => Deprecated
      permittedNumberOfCallsInHalfOpenState: 3 # 반열림 상태에서의 호출 수로, 서킷을 다시 열거나 닫힘 상태로 돌아갈지를 결정할 때 사용 한다.
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
    organizationService:
      registerHealthIndicator: true
      sliding-window-size: 6
      permittedNumberOfCallsInHalfOpenState: 4
      waitDurationInOpenState: 20s
      failureRateThreshold: 60

resilience4j.ratelimiter:
  instances:
    licenseService:
      limitForPeriod: 5
      limitRefreshPeriod: 5000
      timeoutDuration: 1000ms

resilience4j.retry:
  instances:
    retryLicenseService:
      # maxRetryAttempts: 5 => Deprecated
      max-attempts: 5 # 첫번째 호출을 포함한 총 재시도 횟수
      waitDuration: 10000
      retry-exceptions:
        - java.util.concurrent.TimeoutException

resilience4j.bulkhead:
  instances:
    bulkheadLicenseService:
      maxWaitDuration: 2ms
      maxConcurrentCalls: 20


resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadLicenseService:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1