server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
 
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      discovery.locator: # 서비스 ID를 기반으로 요청을 자동으로 라우팅
        enabled: true
        lowerCaseServiceId: true #
      routes: # 여기부터 하위 항목들은 수동 매핑
      - id: organization-service
        uri: lb://organization-service
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path} #
      - id: licensing-service
        uri: lb://licensing-service
        predicates:
        - Path=/license/**
        filters:
        - RewritePath=/license/(?<path>.*), /$\{path}


       
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        - "gateway"
  endpoint:
    gateway:
      enabled: true
        
        