spring:
  application:
    name: config-server
  profiles:
    active: git #native
  cloud:
    config:
      server:
        encrypt.enabled: false
        native:
          search-locations: classpath:/config
        git:
          default-label: master
          uri: https://github.com/klimtever/config.git
          searchPaths: licensingservice
server:
  port: 8071

encrypt:
  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"